bank.resilience.force-legacy-audit-failure=${FORCE_LEGACY_AUDIT_FAILURE:false}
resilience4j.circuitbreaker.instances.legacyAudit.sliding-window-size=4
resilience4j.circuitbreaker.instances.legacyAudit.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.legacyAudit.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.legacyAudit.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.legacyAudit.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.legacyAudit.event-consumer-buffer-size=20
resilience4j.retry.instances.legacyAudit.max-attempts=2
resilience4j.retry.instances.legacyAudit.wait-duration=100ms
resilience4j.retry.instances.legacyAudit.retry-exceptions=java.lang.IllegalStateException
resilience4j.bulkhead.instances.legacyAudit.max-concurrent-calls=5
resilience4j.bulkhead.instances.legacyAudit.max-wait-duration=0
management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents
resilience4j.circuitbreaker.circuit-breaker-aspect-order=1
resilience4j.retry.retry-aspect-order=2
