server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=bancoxyz
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz

bankxyz.auth.web-token=bff-web-token
bankxyz.auth.mobile-token=bff-mobile-token
bankxyz.auth.atm-token=bff-atm-token

bff.security.token.web=token-seguro-web-2024
bff.security.token.mobile=token-seguro-mobile-2024
bff.security.token.atm=token-seguro-atm-2024

server.error.include-message=always